### ISSUE TITLE
Ping is not a constructor

### ISSUE THREAD

**Issue by crlang44** [t1st3/cordova-plugin-ping#8]
I am trying to use ping in my Angular/Cordova application in the following way:

```
let ipList = [{ query: 'www.tiste.org', timeout: 1, retry: 3, version: 'v4' },
            { query: 'www.somesite.com', timeout: 2, 'retry': 3, version: 'v6' }];
            let success = function (results) {
                console.log(results);
            };
            let err = function (e) {
                console.log('Error: ' + e);
            };

            let p = new Ping();
            p.ping(ipList, success, err);
```

But am getting the error:

`ERROR TypeError: Ping is not a constructor`

**Comment by crlang44** [comment]
Imported it with

`import { Ping } from 'cordova-plugin-ping/www/ping';
`
but now I'm getting different errors:

```
ERROR in ./~/cordova-plugin-ping/www/ping.js
Module not found: Error: Can't resolve 'cordova' in 'C:\Users\clang\Desktop\hybrid-connection-alerts\node_modules\cordova-plugin-ping\www'
 @ ./~/cordova-plugin-ping/www/ping.js 4:12-30
 @ ./src/app/login/login.component.ts
 @ ./src/app/login/index.ts
 @ ./src/app/app.module.ts
 @ ./src/app/index.ts
 @ ./src/main.browser.ts

ERROR in ./~/cordova-plugin-ping/www/ping.js
Module not found: Error: Can't resolve 'cordova/exec' in 'C:\Users\clang\Desktop\hybrid-connection-alerts\node_modules\cordova-plugin-ping\www'
 @ ./~/cordova-plugin-ping/www/ping.js 3:9-32
 @ ./src/app/login/login.component.ts
 @ ./src/app/login/index.ts
 @ ./src/app/app.module.ts
 @ ./src/app/index.ts
 @ ./src/main.browser.ts

ERROR in ./~/cordova-plugin-ping/www/ping.js
Module not found: Error: Can't resolve 'cordova/utils' in 'C:\Users\clang\Desktop\hybrid-connection-alerts\node_modules\cordova-plugin-ping\www'
 @ ./~/cordova-plugin-ping/www/ping.js 2:12-36
 @ ./src/app/login/login.component.ts
 @ ./src/app/login/index.ts
 @ ./src/app/app.module.ts
 @ ./src/app/index.ts
 @ ./src/main.browser.ts
```

**Comment by t1st3** [comment]
Actually, creating this plugin, I had no idea how to properly require or import modules while using cordova (and I still don't have much clue about it). This script was mainly built to be used as an inline `<script>` and to expose some globals, which seems to be the problem when you try to import the script with a more modern `import` approach.
Will try to investigate more about importing this module, but feel free to open a PR if you know how to do it properly.

**Comment by crlang44** [comment]
Hmm, I'm now trying to use it as:

`<script type="text/javascript" src="../node_modules/cordova-plugin-ping/www/ping.js"></script>`

from my index.html

but am getting the error:

**Comment by crlang44** [comment]
Yes!!! I have figured it out. Turns out I was doing too much for the importing part of it. No need to import it at all. Just needed to specify `declare var Ping;` at the top of my file so typescript wouldn't throw errors. 

If I get some time, maybe I can create a type definition file for TypeScript and I could submit a PR.

**Comment by crlang44** [comment]
Also for any future person using Angular with this, I had to enclose the content of the success callback in a ngZone like so (don't forget to import ngZone from @angular/core and inject it into your component):

            // Use the Ping plugin to determine if the domain name of the specified
            // host can be resolved. Try using both IPv4 and IPv6.
            let ipList = [
                { query: entry.host, timeout: 2, retry: 2, version: 'v4' },
                { query: entry.host, timeout: 2, retry: 2, version: 'v6' }
            ];

            let ping = new Ping();

            ping.ping(ipList, success => {
                component.ngZone.run(() => {
                    let requestList: any[] = success;
                     ... // The rest of your handling goes here.
               }); // End of Zone
            }, err => console.log(err));

**Comment by t1st3** [comment]
@crlang44 glad you could make it work and sorry not to have been able to help much...
Sure, you can open a PR regarding TypeScript usage. As you may have noticed, I'm not familiar (yet?) with TypeScript, but wanting to learn it for some time, so reviewing your eventual PR may not be immediate.
Thanks for your investigation anyway

**Comment by MarcosLeva** [comment]
did you have to declare the variable ngZone in the constructor?
I also have a problem with "component" ("can not find name 'component'")

**Comment by MarcosLeva** [comment]
![image](https://user-images.githubusercontent.com/44708727/54776091-a1b64780-4bcc-11e9-8e02-9ebaf1c11cb3.png)
